### ISSUE TITLE
 Error connecting: SocketException: OS Error: Connection refused

### ISSUE THREAD

**Issue by andraderaf** [tendermint/flutter#103]
**Desription**

When trying to sign a transaction, I am getting this error :

/flutter ( 3753): gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: OS Error: Connection refused, errno = 111, address = api.devtestnet.pylons.tech, port = 60770, details: null, rawResponse: null, trailers: {})
I/flutter ( 3753): 
I/flutter ( 3753): AlanTransactionSigningFailure{cause: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: OS Error: Connection refused, errno = 111, address = api.devtestnet.pylons.tech, port = 60770, details: null, rawResponse: null, trailers: {})}
I/flutter ( 3753): AlanTransactionSigningFailure{cause: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: OS Error: Connection refused, errno = 111, address = api.devtestnet.pylons.tech, port = 60770, details: null, rawResponse: null, trailers: {})}

I am inclined to think that the problem is in the file :

https://github.com/tendermint/flutter/blob/main/packages/transaction_signing_gateway/lib/alan/alan_credentials_serializer.dart

and that it probably needs to serialize the port information as well, as it seems that AllanSigner is using it somehow and it defaults to 9090 if not found. But this is my assumption. 

**To Reproduce**
1. Use a grpc port different from 9090, the error will likely reproduce.

**Expected behavior**
1. Exception reported above.

**Comment by andrzejchm** [comment]
Hey @andraderaf , thanks for pointing this out! this should be fixed with #104
