### ISSUE TITLE
Getting this error trying to sign my transaction from alan

### ISSUE THREAD

**Issue by kjawadDeveloper2** [tendermint/flutter#106]
gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10)

**Comment by kjawadDeveloper2** [comment]
Looks like something related with https://github.com/grpc/grpc-dart/issues/451

**Comment by kjawadDeveloper1** [comment]
New error : gRPC Error (code: 5, codeName: NOT_FOUND, message: HTTP connection completed with 404 instead of 200, details:…
