### ISSUE TITLE
TransactionSigningFailure type getter throwing

### ISSUE THREAD

**Issue by AndreHaueisen** [tendermint/flutter#186]
**Description**

See [this line](https://github.com/tendermint/flutter/blob/main/packages/transaction_signing_gateway/lib/model/transaction_signing_failure.dart#L42)
The getter should not be throwing

**Comment by andrzejchm** [comment]
definitely, good catch! Thanks for reporting this @AndreHaueisen !

**Comment by AndreHaueisen** [comment]
Sure! 🍻
