### ISSUE TITLE
Call getBalances upon successful transaction broadcast

### ISSUE THREAD

**Issue by andrzejchm** [tendermint/flutter#218]
We can also trigger `getBalances` upon successful transaction broadcast here:  https://github.com/tendermint/flutter/blob/19c6b3bd5bd0e7a29834bc5303a0a5903aa98e7a/starport_template/lib/stores/wallets_store.dart#L211

_Originally posted by @andrzejchm in https://github.com/tendermint/flutter/pull/217#r809677050_

**Comment by Zfinix** [comment]
I believe his has already been merged in?

**Comment by andrzejchm** [comment]
I think it was not implemented yet and the issue is still valid

**Comment by Zfinix** [comment]
<img width="610" alt="Screenshot 2022-03-28 at 9 03 04 AM" src="https://user-images.githubusercontent.com/25801929/160353597-b45093e7-b161-43d0-9e94-260d0b2cb7ae.png">
@andrzejchm  I just checked and it has been merged in already

**Comment by andrzejchm** [comment]
we're good to close this one then :)
