### ISSUE TITLE
feat: Mnemonic generation

### ISSUE THREAD

**Issue by wal33d006** [tendermint/flutter#28]
The app should generate a mnemonic for the user during the first time run, which should be stored in a secure storage.

**Comment by fadeev** [comment]
I would add that there should be two options: import exiting mnemonic or create a new account (we generate mnemonic for the user).

**Comment by wal33d006** [comment]
Yes, the "importing wallet" thing remains the same as before.

**Comment by wal33d006** [comment]
Just a question, Demeris app is going to either import, or create a new wallet first time for the user and then the user is going to be directly logged in to the app next time he/she runs the app, is that so? If yes, then we would also have to implement the password thing. When the user opens the app again, he/she enters the password to unlock the wallet.
Just want to know if all of that has to be done.
@fadeev

**Comment by fadeev** [comment]
Yes, we definitely need to add setting the password, because the mnemonic has to be stored symmetrically encrypted with a password.

**Comment by wal33d006** [comment]
There is a [package](https://pub.dev/packages/encrypt) in dart which can be used for encryption. This is one way of doing that symmetrically. My naive question: Given this package, does the password have to be converted to a 32 length string and used as a key in this code? 

<img width="787" alt="Screenshot 2021-06-11 at 2 38 02 PM" src="https://user-images.githubusercontent.com/25613623/121666482-bdb2a600-cac2-11eb-91e1-57a04e8d8ebf.png">
@fadeev

**Comment by fadeev** [comment]
I think we should encrypt with the exact password provided by the user. Having a char requirement is an odd thing to do for a library.
