### ISSUE TITLE
CI: Investigate adding app previews

### ISSUE THREAD

**Issue by fadeev** [tendermint/flutter#4]
Set up a system where users/developers (stakeholders) who don't have the ability to build and run the project on their machine can preview the app, either by installing it on their phone or viewing it on the web (that could be a good first step).

For `tendermint/vue` we're using Netlify, maybe there is something similar for Flutter projects.

**Comment by wal33d006** [comment]
@fadeev 
Netlify is available for Flutter as well (just researched it), and it can be triggered on every new merge to `main` branch and automatically deploys the latest web code. The are two problems I see right now:

- Mobile app currently connects to starport localhost links for getting wallet balances and sending transactions. If that is deployed, it won't work. Are we going to connect it to the deployed version of starport?
- The app preview will be web based, that means it will be a website created in Flutter, not a native mobile app. For native mobile app, we either need to distribute it after getting peoples' email IDs or publish an Android APK somewhere which can be downloaded by Android users to test. And I believe this can only be done for Android and not for iOS, to distribute iOS we will be needing a proper paid account and email IDs of Apple ID users.

**Comment by fadeev** [comment]
I propose we then do it first for the web only (and consider distributing APKs later down the line). For Netlify deploy-previews to work we'll need to make it possible to choose environments: either local endpoints (if you're working on the Flutter project locally) or connect to [a running Cosmos Hub testnet](http://tutorials.cosmos.network/connecting-to-testnet/) (so that web version can fetch data).

We have this implemented for Vue with env variables:

https://github.com/tendermint/vue/blob/develop/packages/template/.env.spn

https://cli.vuejs.org/guide/mode-and-env.html

I'm sure there is a way to do it in Flutter as well 🙂

**Comment by wal33d006** [comment]
Splitting this into two. Added #6 for environment variables part
